### PR TITLE
✨ Support multiple databases

### LINKED ISSUE #6: cannot connect to multiple dbs
I get `(node:1265) UnhandledPromiseRejectionWarning: MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections`

### PR DESCRIPTION
**Pull request by Androz2091**
Closes #6

### CODE REVIEW

**Comment by Androz2091** [comment]
It should work but I wasn't able to test it (I will try to have the time)

**Comment by reallyfionn** [comment]
Ok so when can we expect this to be updated?

**Comment by Snowflake107** [comment]
next week

**Comment by reallyfionn** [comment]
Cool, thanks!

**Comment by wolfier74** [comment]
When this will be merged?

**Pull request closed without merging**
